In [1]:
%config Completer.use_jedi = True

In [2]:
import numpy as np
import cv2

In [17]:
img = cv2.imread('./data/friends.jpg')
cv2.imshow('image', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# load cascade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [12]:
print(face_rect)

[[164 144  84  84]
 [266  66  84  84]
 [405 150  71  71]
 [262 273  71  71]
 [400 335  91  91]
 [130 311  77  77]]


In [19]:
# convert image to greyscale
grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# apply cascade classifier on grayscale(detect face)
face_rect = haar.detectMultiScale(grey)
# draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0))
    cv2.imshow('detected faces', img)
    cv2.waitKey()
    cv2.destroyAllWindows()
