In [1]:
%config Completer.use_jedi = True

In [20]:
import numpy as np
import cv2

In [21]:
img = cv2.imread('./data/friends.jpg')
cv2.imshow('image', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
# load cascade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [23]:
print(face_rect)

[[127   4  66  66]
 [128 107  97  97]
 [256  90  95  95]
 [406  92  96  96]]


In [19]:
# convert image to greyscale
grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# apply cascade classifier on grayscale(detect face)
face_rect = haar.detectMultiScale(grey)
# draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0))
    ## crop female faces
    roi = img_rg
    cv2.imshow('detected faces', img)
    cv2.waitKey()
    cv2.destroyAllWindows()
